- app/payment-request-mapping/index.js
- package-lock.json
- package.json
- test/integration/local/consuming/save-payment-request.test.js
https://eaflood.atlassian.net/browse/SFI-906
> Map fund code

- app/errors.js
- app/messaging/process-acknowledgement-message.js
- app/messaging/process-payment-message.js
- app/messaging/process-quality-check-message.js
- app/messaging/process-return-message.js
- app/messaging/update-requests-awaiting-debt-data.js
- package-lock.json
- package.json
- test/unit/messaging/process-acknowledgement-message.test.js
- test/unit/messaging/process-payment-message.test.js
- test/unit/messaging/process-quality-check-message.test.js
- test/unit/messaging/process-return-message.test.js
https://eaflood.atlassian.net/browse/SFI-1509﻿
> Improve message retention

- app/holds/get-holds.js
- package.json
https://eaflood.atlassian.net/browse/SFI-1753﻿
> Only expose open holds

- app/processing/confirm-due-dates.js
- docs/asyncapi.yaml
- package.json
- test/integration/local/settlement.test.js
- test/unit/processing/confirm-due-dates.test.js
https://eaflood.atlassian.net/browse/SFI-1878
> Fix balloon reduction use of DAX codes

- app/event/raise-events.js
- app/event/send-publishing-events.js
- app/messaging/get-pending-payment-requests.js
- app/messaging/index.js
- app/messaging/outbox.js
- package-lock.json
- package.json
- Fix concurrency of publishing
- Fix concurrency issue
> Fix concurrency

- app/event/send-publishing-events.js
- package-lock.json
- package.json
- Fix event reference
- Fix event reference
> Fix event reference

- helm/ffc-pay-processing/templates/config-map.yaml
- package-lock.json
- package.json
- Reduce dependency on App Config
- Update Helm
> Reduce dependency on App Config

- README.md
- app/event/send-processing-return-event.js
- app/messaging/process-return-message.js
- app/settlement.js
- package.json
- test/integration/local/settlement.test.js
- test/unit/messaging/process-return-message.test.js
https://eaflood.atlassian.net/browse/SFI-1966
> Processing service should handle no matching settlement without throwing error

- changelog/db.changelog-1.25.xml
- changelog/db.changelog.xml
- package.json
https://eaflood.atlassian.net/browse/SFI-1823
﻿
> Add additional schemes

- changelog/db.changelog-1.29.xml
- changelog/db.changelog.xml
- package.json
https://eaflood.atlassian.net/browse/SFI-2202
> Add Vet Visit assurance check hold

- app/data/models/completed-payment-request.js
- app/data/models/payment-request.js
- changelog/db.changelog-1.32.xml
- changelog/db.changelog.xml
- package.json
https://dev.azure.com/defragovuk/DEFRA-FFC/_workitems/edit/121617﻿
> Use UUID data types

- changelog/db.changelog-1.33.xml
- changelog/db.changelog-1.34.xml
- changelog/db.changelog-1.35.xml
- changelog/db.changelog.xml
- package.json
Ticket links:
- https://dev.azure.com/defragovuk/DEFRA-FFC/_sprints/taskboard/DEFRA-FFC%20Payments%20Team/DEFRA-FFC/Payment%20Service/Sprint%2002?workitem=158553
- https://dev.azure.com/defragovuk/DEFRA-FFC/_sprints/taskboard/DEFRA-FFC%20Payments%20Team/DEFRA-FFC/Payment%20Service/Sprint%2002?workitem=158552
- https://dev.azure.com/defragovuk/DEFRA-FFC/_sprints/taskboard/DEFRA-FFC%20Payments%20Team/DEFRA-FFC/Payment%20Service/Sprint%2002?workitem=158554
> Added CS hold categories

- app/holds/add-hold.js
- app/holds/remove-hold.js
- package.json
https://dev.azure.com/defragovuk/DEFRA-FFC/_workitems/edit/158695
Event format for hold is incorrect as sends full sequelize object.
> Fix format of hold event

- docs/asyncapi.yaml
- package.json
https://dev.azure.com/defragovuk/DEFRA-FFC/_workitems/edit/164440
> Update Async API Spec

- app/constants/schemes.js
- changelog/db.changelog-1.36.xml
- changelog/db.changelog.xml
- package.json
https://dev.azure.com/defragovuk/DEFRA-FFC/_workitems/edit/158557
> Add support for FDMR

- app/data/models/completed-payment-request.js
- app/data/models/payment-request.js
- changelog/db.changelog-1.38.xml
- changelog/db.changelog.xml
- docs/asyncapi.yaml
- package.json
https://dev.azure.com/defragovuk/DEFRA-FFC/_sprints/taskboard/DEFRA-FFC%20Payments%20Team/DEFRA-FFC/Payment%20Service/Sprint%2002?workitem=166913
>  166913-include-advance-payment-status-in-cs

- app/constants/schemes.js
- app/processing/map-account-codes.js
- changelog/db.changelog-1.39.xml
- changelog/db.changelog.xml
- package.json
- test/unit/processing/map-account-codes.test.js
https://dev.azure.com/defragovuk/DEFRA-FFC/_sprints/taskboard/DEFRA-FFC%20Payments%20Team/DEFRA-FFC/Payment%20Service/Sprint%2003?workitem=158579
> 158579-calc-manual-invoices

- app/constants/schemes.js
- app/processing/account-codes/maps/get-map.js
- changelog/db.changelog-1.51.xml
- changelog/db.changelog.xml
- package.json
- test/helpers/reset-database.js
- test/integration/local/schemes/get-schemes.test.js
- test/mocks/payment-requests/sfi23.js
- test/mocks/schemes/sfi23.js
- test/unit/processing/account-codes/maps/get-map.test.js
https://dev.azure.com/defragovuk/DEFRA-FFC/_workitems/edit/213682
> Add SFI 23

- app/processing/is-agreement-closed.js
- package.json
- test/unit/processing/is-agreement-closed.test.js
https://dev.azure.com/defragovuk/DEFRA-FFC/_workitems/edit/242952
> only perform AR removal if total value is 0

- changelog/db.changelog-1.58.xml
- changelog/db.changelog.xml
- package.json
> Add SFI23 hold

- app/processing/due-dates/handle-sfi23-advance-payments.js
- package.json
- test/unit/processing/due-dates/handle-sfi23-advance-payments.test.js
https://dev.azure.com/defragovuk/DEFRA-FFC/_workitems/edit/255883
> amend schedule for SFI23 advance payments

- changelog/db.changelog-1.66.xml
- changelog/db.changelog.xml
- package.json
https://dev.azure.com/defragovuk/DEFRA-FFC/_workitems/edit/307308
> Add index for migrationId

- app/processing/dual-accounting/get-previous-domestic-fund.js
- package.json
- test/unit/processing/dual-accounting/get-previous-domestic-fund.test.js
https://eaflood.atlassian.net/browse/DOC-870
> exclude EXQ00 from previous domestic fund code checks

- app/routing/reset-due-dates-for-sfi23.js
- app/routing/transform-payment-request.js
- package.json
- test/unit/routing/reset-due-dates-for-sfi23.test.js
https://eaflood.atlassian.net/browse/DOC-931
> add due date reset for request editor routed SFI23 PPAs with Advance Payments

- app/settlement/adjust-settlement-value.js
- package.json
- test/integration/local/settlement/adjust-settlement-value.test.js
https://eaflood.atlassian.net/browse/DOC-905
> change flooring to rounding for exchange rate payments

- app/constants/schedules.js
- app/processing/due-dates/get-payment-schedule.js
- package.json
- test/integration/narrow/processing/due-dates/confirm-due-dates.test.js
- test/unit/processing/due-dates/get-payment-schedule.test.js
https://eaflood.atlassian.net/browse/DOC-1053
> amend Y2 schedule

- app/constants/schemes.js
- app/processing/account-codes/maps/get-map.js
- app/processing/delta/invoice-number/create-split-invoice-number.js
- changelog/db.changelog-1.71.xml
- changelog/db.changelog-1.72.xml
- changelog/db.changelog.xml
- package-lock.json
- package.json
- test/helpers/reset-database.js
- test/integration/local/schemes/get-schemes.test.js
- test/mocks/payment-requests/sfi-expanded.js
- test/mocks/schemes/sfi-expanded.js
- test/unit/processing/account-codes/maps/get-map.test.js
https://eaflood.atlassian.net/browse/DOC-1037
https://eaflood.atlassian.net/browse/DOC-1043
https://eaflood.atlassian.net/browse/DOC-1030
> add sfi expanded offer

- app/constants/events.js
- app/event/send-return-event.js
- app/messaging/process-return-message.js
- package-lock.json
- package.json
- test/unit/event/send-return-event.test.js
https://eaflood.atlassian.net/browse/DOC-1323
> add alerting for unsettled payment requests

- app/holds/get-holds.js
- app/server/routes/holds.js
- package.json
- test/integration/local/holds/get-holds.test.js
https://eaflood.atlassian.net/browse/DOC-610
> allow page blocks of holds

- README.md
- docker-compose.acceptance.yaml
- docker-compose.debug.yaml
- docker-compose.link.yaml
- docker-compose.migrate.yaml
- docker-compose.override.yaml
- docker-compose.test.debug.yaml
- docker-compose.test.watch.yaml
- docker-compose.test.yaml
- docker-compose.yaml
- package.json
- scripts/acceptance
- scripts/start
- scripts/test
- Removed version 
- Moved from docker-compose to docker compose
> DOC-1417 : moved command docker-compose to docker compose and removed version

- .devcontainer/devcontainer.json
- .devcontainer/docker-compose.yml
- .github/dependabot.yml
- .pre-commit-config.yaml
- .secrets.baseline
- Dockerfile
- package-lock.json
- package.json
> Added devcontainer config

- changelog/db.changelog-1.78.xml
- changelog/db.changelog.xml
- package.json
https://eaflood.atlassian.net/browse/DOC-1615
> add migration holds

- app/acknowledgement/process-acknowledgement.js
- app/acknowledgement/process-invalid.js
- app/event/send-ack-invalid-bank-details-error-event.js
- app/event/send-acknowledgement-error-event.js
- package.json
- test/unit/acknowledgement/process-acknowledgement.test.js
- test/unit/acknowledgement/process-invalid.test.js
- test/unit/event/send-ack-invalid-bank-details-error-event.test.js
- test/unit/event/send-acknowledgement-error-event.test.js
https://eaflood.atlassian.net/browse/DOC-1668
> add source system to invalid bank alerts

- app/acknowledgement/process-acknowledgement.js
- app/acknowledgement/process-invalid.js
- app/event/send-ack-invalid-bank-details-error-event.js
- app/event/send-acknowledgement-error-event.js
- package.json
- test/unit/acknowledgement/process-acknowledgement.test.js
- test/unit/acknowledgement/process-invalid.test.js
- test/unit/event/send-ack-invalid-bank-details-error-event.test.js
- test/unit/event/send-acknowledgement-error-event.test.js
https://eaflood.atlassian.net/browse/DOC-1719
> include additional information in D365 invalid bank alerts

- changelog/db.changelog-1.79.xml
- changelog/db.changelog.xml
- package-lock.json
- package.json
https://eaflood.atlassian.net/browse/DOC-1783
> add bank account anomaly for ES

- app/auto-hold/add-hold.js
- app/auto-hold/apply-hold.js
- app/auto-hold/get-existing-hold.js
- app/auto-hold/remove-auto-hold.js
- app/constants/get-scheduled-payment-requests-query.js
- app/data/models/auto-hold.js
- app/holds/get-holds.js
- changelog/db.changelog-1.81.xml
- changelog/db.changelog.xml
- package-lock.json
- package.json
- test/integration/local/auto-hold/remove-auto-hold.test.js
- test/mocks/holds/auto-hold.js
- test/mocks/holds/hold-category.js
- test/unit/auto-hold/add-hold.test.js
- test/unit/auto-hold/get-existing-hold.test.js
https://eaflood.atlassian.net/browse/DOC-1892
Script:
[ffc-pay-processing-SPS1.xxx.agreement.txt](https://github.com/user-attachments/files/18966562/ffc-pay-processing-SPS1.xxx.agreement.txt)
> introduce contractNumber (claim id) to auto holds

- changelog/db.changelog-1.83.xml
- changelog/db.changelog.xml
- package-lock.json
- package.json
https://eaflood.atlassian.net/browse/DOC-1981
> add bank account anomaly hold for imps

- changelog/db.changelog-1.84.xml
- changelog/db.changelog.xml
- package-lock.json
- package.json
Adding new Hold Type from SFI-23: "Partial Recovery Process".
https://eaflood.atlassian.net/browse/DOC-2015
> Partial recovery process holdtype

- changelog/db.changelog-1.85.xml
- changelog/db.changelog.xml
- package-lock.json
- package.json
https://eaflood.atlassian.net/browse/DOC-2037
SQL script required:
[ffc-pay-processing-SPS-lift-auto-holds.txt](https://github.com/user-attachments/files/20210981/ffc-pay-processing-SPS-lift-auto-holds.txt)
> clear erroneous legacy holds
